apiVersion: v1
kind: ConfigMap
metadata:
  name: option1-config
  namespace: option1
data:
  GEMINI_LLM_MODEL: gemini-3-flash-preview
  GEMINI_EMB_MODEL: models/gemini-embedding-001
  MILVUS_HOST: milvus-svc.option1.svc.cluster.local
  MILVUS_PORT: "19530"
  MILVUS_COLLECTION: paper_chunks
  MILVUS_DIMENSION: "3072"
  TOP_K: "4"
  CHUNK_SIZE: "900"
  CHUNK_OVERLAP: "150"
  TRANSLATOR_BASE_URL: http://translator-svc.option1.svc.cluster.local:8000
