apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: option1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: us-central1-docker.pkg.dev/nih-cl-odss-yiqingz2o-65d7/option1/frontend@sha256:b62a4453f97839ad969ac6658f62dd534bcf6f7a3efba8f4f53d2716a3679ea8
          imagePullPolicy: Always
          ports:
            - containerPort: 8501
          env:
            - name: AGENT_BASE_URL
              value: http://agent-svc.option1.svc.cluster.local:8080
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          readinessProbe:
            httpGet:
              path: /
              port: 8501
            initialDelaySeconds: 20
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: option1
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - name: http
      port: 80
      targetPort: 8501
