apiVersion: v1
kind: Secret
metadata:
  name: option1-secrets
  namespace: option1
type: Opaque
stringData:
  GOOGLE_API_KEY: "AIXXXXXXXXXXXXXX" ## Replace with your actual Google API key
  MILVUS_USERNAME: ""
  MILVUS_PASSWORD: ""
