apiVersion: v1
kind: Secret
metadata:
  name: option1-secrets
  namespace: option1
type: Opaque
stringData:
  GOOGLE_API_KEY: "AIzaSyAqwxDKzIDp3ZMSSd3Gi3OvuRGYjW5SCHU"
  MILVUS_USERNAME: ""
  MILVUS_PASSWORD: ""
